# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HamuHamu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HamuHamu

  pod 'SwiftyGif'
  pod 'RealmSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'

end
