# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HamuHamu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HamuHamu

  pod 'SwiftyGif'
  pod 'RealmSwift'
  pod 'SwiftSoup'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'

post_install do |installer|
installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
 end

 if target.name == 'BoringSSL-GRPC'
   target.source_build_phase.files.each do |file|
     if file.settings && file.settings['COMPILER_FLAGS']
       flags = file.settings['COMPILER_FLAGS'].split
       flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
       file.settings['COMPILER_FLAGS'] = flags.join(' ')
     end
   end
 end
end
end

end
